// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "luyoung",
            "email": "luyoung0001@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/chinese": {
            "get": {
                "description": "根据传入的中文单词查询对应的英语翻译",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "查询中文翻译的英语单词",
                "parameters": [
                    {
                        "type": "string",
                        "description": "中文单词",
                        "name": "chinese",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询成功",
                        "schema": {
                            "$ref": "#/definitions/service.SearchResponse"
                        }
                    },
                    "400": {
                        "description": "查询失败",
                        "schema": {
                            "$ref": "#/definitions/service.SearchResponse"
                        }
                    }
                }
            }
        },
        "/english": {
            "get": {
                "description": "根据传入的英文单词查询对应的英语翻译",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "查询英文单词的一切信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "英文单词",
                        "name": "english",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询成功",
                        "schema": {
                            "$ref": "#/definitions/service.SearchResponse"
                        }
                    },
                    "400": {
                        "description": "查询失败",
                        "schema": {
                            "$ref": "#/definitions/service.SearchResponse"
                        }
                    }
                }
            }
        },
        "/word": {
            "get": {
                "description": "根据传入的英语单词查询对应的中文翻译",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "查询英语单词的中文翻译",
                "parameters": [
                    {
                        "type": "string",
                        "description": "英语单词",
                        "name": "english",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询成功",
                        "schema": {
                            "$ref": "#/definitions/service.SearchResponse"
                        }
                    },
                    "400": {
                        "description": "查询失败",
                        "schema": {
                            "$ref": "#/definitions/service.SearchResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "service.SearchResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据"
                },
                "message": {
                    "description": "消息",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "OpenAPI"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9000",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "trans_api",
	Description:      "This is a celler server",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
